/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.anthonyponte.jepinsa.view;

import com.anthonyponte.jepinsa.model.Tipo;
import com.anthonyponte.jepinsa.model.TipoOperacion;
import com.anthonyponte.jepinsa.model.UnidadMedida;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.text.SimpleDateFormat;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListCellRenderer;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JSeparator;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import org.jdesktop.swingx.JXDatePicker;
import org.kordamp.ikonli.remixicon.RemixiconAL;
import org.kordamp.ikonli.remixicon.RemixiconMZ;
import org.kordamp.ikonli.swing.FontIcon;

/**
 *
 * @author anthony
 */
public class FacturaIFrame extends JInternalFrame {

    /**
     * Creates new form VoidedDocumentsIFrame
     */
    public FacturaIFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbed = new JTabbedPane();
        pnlEncabezado = new JPanel();
        lblFecha = new JLabel();
        dpFecha = new JXDatePicker();
        lblTipo = new JLabel();
        cbxTipo = new JComboBox<>();
        lblCorrelativo = new JLabel();
        tfCorrelativo = new JTextField();
        lblSerie = new JLabel();
        cbxMoneda = new JComboBox<>();
        lblMoneda = new JLabel();
        cbxSerie = new JComboBox<>();
        cbxTipoOperacion = new JComboBox<>();
        lblTipoOperacion = new JLabel();
        pnlAdquiriente = new JPanel();
        btnAdquirienteDocumentoIdentidad = new JButton();
        tfAdquirienteDocumentoIdentidad = new JTextField();
        cbxAdquirienteTipoDocumentoIdentidad = new JComboBox<>();
        lblAdquirienteTipoDocumentoIdentidad = new JLabel();
        tfAdquirienteNombre = new JTextField();
        lblAdquirienteNombre = new JLabel();
        pnlDetalle = new JPanel();
        lblUnidadMedida = new JLabel();
        cbxUnidadMedida = new JComboBox<>();
        lblCantidad = new JLabel();
        tfCantidad = new JTextField();
        lblDescripcion = new JLabel();
        tfDescripcion = new JTextField();
        separator = new JSeparator();
        btnNuevo = new JButton();
        btnGuardar = new JButton();
        btnLimpiar = new JButton();

        setClosable(true);
        setIconifiable(true);
        setFrameIcon(FontIcon.of(RemixiconAL.ADD_LINE, 16, Color.decode("#f7d117")));
        setMaximumSize(null);
        setMinimumSize(null);

        tabbed.setMaximumSize(null);

        pnlEncabezado.setMaximumSize(null);

        lblFecha.setFont(lblFecha.getFont().deriveFont(lblFecha.getFont().getStyle() | Font.BOLD, lblFecha.getFont().getSize()-2));
        lblFecha.setText("Fecha emision *");

        dpFecha.setEditable(false);
        dpFecha.setEnabled(false);
        dpFecha.setFormats(new SimpleDateFormat("d MMMM y hh:mm:ss"));
        dpFecha.setMaximumSize(null);
        dpFecha.setMinimumSize(null);
        dpFecha.setPreferredSize(new Dimension(150, 30));

        lblTipo.setFont(lblTipo.getFont().deriveFont(lblTipo.getFont().getStyle() | Font.BOLD, lblTipo.getFont().getSize()-2));
        lblTipo.setText("Tipo *");

        cbxTipo.setModel(new DefaultComboBoxModel(new Tipo[] {
            new Tipo("01", "Factura"),
            new Tipo("03", "Boleta de venta")
        }));
        cbxTipo.setSelectedIndex(-1);
        cbxTipo.setEnabled(false);
        cbxTipo.setMaximumSize(null);
        cbxTipo.setPreferredSize(new Dimension(150, 30));
        cbxTipo.setRenderer(new DefaultListCellRenderer(){
            @Override
            public Component getListCellRendererComponent(
                JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (value instanceof Tipo) {
                    Tipo tipoDocumento = (Tipo) value;
                    setText(tipoDocumento.getDescripcion());
                }
                return this;
            }
        });

        lblCorrelativo.setFont(lblCorrelativo.getFont().deriveFont(lblCorrelativo.getFont().getStyle() | Font.BOLD, lblCorrelativo.getFont().getSize()-2));
        lblCorrelativo.setText("Correlativo *");
        lblCorrelativo.setName(""); // NOI18N

        tfCorrelativo.setEnabled(false);
        tfCorrelativo.setMaximumSize(null);
        tfCorrelativo.setMinimumSize(null);
        tfCorrelativo.setPreferredSize(new Dimension(150, 30));
        tfCorrelativo.setEditable(false);

        lblSerie.setFont(lblSerie.getFont().deriveFont(lblSerie.getFont().getStyle() | Font.BOLD, lblSerie.getFont().getSize()-2));
        lblSerie.setText("Serie *");

        cbxMoneda.setModel(new DefaultComboBoxModel(new Tipo[] {
            new Tipo("PEN", "Soles"),
            new Tipo("USD", "Dolares")}));
cbxMoneda.setEnabled(false);
cbxMoneda.setMaximumSize(null);
cbxMoneda.setMinimumSize(null);
cbxMoneda.setPreferredSize(new Dimension(150, 30));
cbxMoneda.setRenderer(new DefaultListCellRenderer(){
    @Override
    public Component getListCellRendererComponent(
        JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
        super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
        if (value instanceof Tipo) {
            Tipo moneda = (Tipo) value;
            setText(moneda.getDescripcion());
        }
        return this;
    }
    });

    lblMoneda.setFont(lblMoneda.getFont().deriveFont(lblMoneda.getFont().getStyle() | Font.BOLD, lblMoneda.getFont().getSize()-2));
    lblMoneda.setText("Moneda *");

    cbxSerie.setModel(new DefaultComboBoxModel<>(new String[] { "FEP1", "FEP2", "FEF1", "FEF2", "FEX1", "FEX2" }));
    cbxSerie.setSelectedIndex(-1);
    cbxSerie.setEnabled(false);
    cbxSerie.setMaximumSize(null);
    cbxSerie.setPreferredSize(new Dimension(150, 30));

    cbxTipoOperacion.setModel(new DefaultComboBoxModel(new Tipo[] {
        new TipoOperacion("0101", "Venta interna"),
        new TipoOperacion("0200", "Exportación de Bienes")}));
cbxTipoOperacion.setEnabled(false);
cbxTipoOperacion.setMaximumSize(null);
cbxTipoOperacion.setMinimumSize(null);
cbxTipoOperacion.setPreferredSize(new Dimension(150, 30));
cbxTipoOperacion.setRenderer(new DefaultListCellRenderer(){
@Override
public Component getListCellRendererComponent(
    JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
    super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
    if (value instanceof TipoOperacion) {
        TipoOperacion tipoOperacion = (TipoOperacion) value;
        setText(tipoOperacion.getDescripcion());
    }
    return this;
    }
    });

    lblTipoOperacion.setFont(lblTipoOperacion.getFont().deriveFont(lblTipoOperacion.getFont().getStyle() | Font.BOLD, lblTipoOperacion.getFont().getSize()-2));
    lblTipoOperacion.setText("Tipo Operacion *");

        GroupLayout pnlEncabezadoLayout = new GroupLayout(pnlEncabezado);
    pnlEncabezado.setLayout(pnlEncabezadoLayout);
    pnlEncabezadoLayout.setHorizontalGroup(pnlEncabezadoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
        .addGroup(pnlEncabezadoLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(pnlEncabezadoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addComponent(cbxTipo, 0, 450, Short.MAX_VALUE)
                .addComponent(tfCorrelativo, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dpFecha, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTipo)
                .addComponent(lblFecha)
                .addComponent(lblSerie)
                .addComponent(lblCorrelativo)
                .addComponent(lblMoneda)
                .addComponent(cbxMoneda, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbxSerie, GroupLayout.Alignment.TRAILING, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTipoOperacion)
                .addComponent(cbxTipoOperacion, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
    );
    pnlEncabezadoLayout.setVerticalGroup(pnlEncabezadoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
        .addGroup(pnlEncabezadoLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(lblFecha)
            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(dpFecha, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(lblTipo)
            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(cbxTipo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(lblSerie)
            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(cbxSerie, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
            .addGap(12, 12, 12)
            .addComponent(lblCorrelativo)
            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(tfCorrelativo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(lblMoneda)
            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(cbxMoneda, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(lblTipoOperacion)
            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(cbxTipoOperacion, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
    );

    cbxMoneda.setSelectedIndex(-1);
    cbxMoneda.setSelectedIndex(-1);

    tabbed.addTab("Encabezado", FontIcon.of(RemixiconAL.FILE_LIST_LINE, 16, Color.decode("#FFFFFF")), pnlEncabezado, "");

    btnAdquirienteDocumentoIdentidad.setIcon(FontIcon.of(RemixiconMZ.SEARCH_2_LINE, 16, Color.decode("#FFFFFF")));
    btnAdquirienteDocumentoIdentidad.setText("Numero *");
    btnAdquirienteDocumentoIdentidad.setEnabled(false);
    btnAdquirienteDocumentoIdentidad.setPreferredSize(new Dimension(125, 30));

    tfAdquirienteDocumentoIdentidad.setEnabled(false);
    tfAdquirienteDocumentoIdentidad.setMaximumSize(null);
    tfAdquirienteDocumentoIdentidad.setMinimumSize(null);
    tfAdquirienteDocumentoIdentidad.setPreferredSize(new Dimension(150, 30));

    cbxAdquirienteTipoDocumentoIdentidad.setModel(new DefaultComboBoxModel(new Tipo[] {
        new Tipo("0", "DOC.TRIB.NO.DOM.SIN.RUC"),
        new Tipo("1", "Documento Nacional de Identidad"),
        new Tipo("4", "Carnet de extranjería"),
        new Tipo("6", "Registro Unico de Contributentes")
    }));
    cbxAdquirienteTipoDocumentoIdentidad.setEnabled(false);
    cbxAdquirienteTipoDocumentoIdentidad.setMaximumSize(null);
    cbxAdquirienteTipoDocumentoIdentidad.setName(""); // NOI18N
    cbxAdquirienteTipoDocumentoIdentidad.setPreferredSize(new Dimension(150, 30));
    cbxAdquirienteTipoDocumentoIdentidad.setRenderer(new DefaultListCellRenderer(){
        @Override
        public Component getListCellRendererComponent(
            JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
            super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
            if (value instanceof Tipo) {
                Tipo tipo = (Tipo) value;
                setText(tipo.getDescripcion());
            }
            return this;
        }
    });

    lblAdquirienteTipoDocumentoIdentidad.setFont(lblAdquirienteTipoDocumentoIdentidad.getFont().deriveFont(lblAdquirienteTipoDocumentoIdentidad.getFont().getStyle() | Font.BOLD, lblAdquirienteTipoDocumentoIdentidad.getFont().getSize()-2));
    lblAdquirienteTipoDocumentoIdentidad.setText("Documento identidad *");

    tfAdquirienteNombre.setEnabled(false);
    tfAdquirienteNombre.setMaximumSize(null);
    tfAdquirienteNombre.setMinimumSize(null);
    tfAdquirienteNombre.setPreferredSize(new Dimension(150, 30));

    lblAdquirienteNombre.setFont(lblAdquirienteNombre.getFont().deriveFont(lblAdquirienteNombre.getFont().getStyle() | Font.BOLD, lblAdquirienteNombre.getFont().getSize()-2));
    lblAdquirienteNombre.setText("Nombre *");

        GroupLayout pnlAdquirienteLayout = new GroupLayout(pnlAdquiriente);
    pnlAdquiriente.setLayout(pnlAdquirienteLayout);
    pnlAdquirienteLayout.setHorizontalGroup(pnlAdquirienteLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
        .addGroup(pnlAdquirienteLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(pnlAdquirienteLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addComponent(cbxAdquirienteTipoDocumentoIdentidad, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tfAdquirienteDocumentoIdentidad, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAdquirienteTipoDocumentoIdentidad)
                .addComponent(btnAdquirienteDocumentoIdentidad, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(tfAdquirienteNombre, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAdquirienteNombre))
            .addContainerGap())
    );
    pnlAdquirienteLayout.setVerticalGroup(pnlAdquirienteLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
        .addGroup(pnlAdquirienteLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(lblAdquirienteTipoDocumentoIdentidad)
            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(cbxAdquirienteTipoDocumentoIdentidad, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(btnAdquirienteDocumentoIdentidad, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(tfAdquirienteDocumentoIdentidad, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(lblAdquirienteNombre)
            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(tfAdquirienteNombre, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
    );

    cbxAdquirienteTipoDocumentoIdentidad.setSelectedIndex(-1);

    tabbed.addTab("Adquiriente", FontIcon.of(RemixiconAL.BUILDING_LINE, 16, Color.decode("#FFFFFF")), pnlAdquiriente);

    lblUnidadMedida.setFont(lblUnidadMedida.getFont().deriveFont(lblUnidadMedida.getFont().getStyle() | Font.BOLD, lblUnidadMedida.getFont().getSize()-2));
    lblUnidadMedida.setText("Unidad medida *");

    cbxUnidadMedida.setModel(new DefaultComboBoxModel(new UnidadMedida[] {
        new UnidadMedida("NIU", "Unidades"),
        new UnidadMedida("CA", "Lata"),
        new UnidadMedida("BX", "Caja")
    }));
    cbxUnidadMedida.setSelectedIndex(-1);
    cbxUnidadMedida.setEnabled(false);
    cbxUnidadMedida.setMaximumSize(null);
    cbxUnidadMedida.setPreferredSize(new Dimension(150, 30));
    cbxUnidadMedida.setRenderer(new DefaultListCellRenderer(){
        @Override
        public Component getListCellRendererComponent(
            JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
            super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
            if (value instanceof UnidadMedida) {
                UnidadMedida unidadMedida = (UnidadMedida) value;
                setText(unidadMedida.getDescripcion());
            }
            return this;
        }
    });

    lblCantidad.setFont(lblCantidad.getFont().deriveFont(lblCantidad.getFont().getStyle() | Font.BOLD, lblCantidad.getFont().getSize()-2));
    lblCantidad.setText("Cantidad *");
    lblCantidad.setName(""); // NOI18N

    tfCantidad.setEnabled(false);
    tfCantidad.setMaximumSize(null);
    tfCantidad.setMinimumSize(null);
    tfCantidad.setPreferredSize(new Dimension(150, 30));

    lblDescripcion.setFont(lblDescripcion.getFont().deriveFont(lblDescripcion.getFont().getStyle() | Font.BOLD, lblDescripcion.getFont().getSize()-2));
    lblDescripcion.setText("Descripcion *");
    lblDescripcion.setName(""); // NOI18N

    tfDescripcion.setEnabled(false);
    tfDescripcion.setMaximumSize(null);
    tfDescripcion.setMinimumSize(null);
    tfDescripcion.setPreferredSize(new Dimension(150, 30));

        GroupLayout pnlDetalleLayout = new GroupLayout(pnlDetalle);
    pnlDetalle.setLayout(pnlDetalleLayout);
    pnlDetalleLayout.setHorizontalGroup(pnlDetalleLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
        .addGroup(pnlDetalleLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(pnlDetalleLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addComponent(cbxUnidadMedida, 0, 450, Short.MAX_VALUE)
                .addComponent(lblUnidadMedida)
                .addComponent(tfCantidad, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCantidad)
                .addComponent(tfDescripcion, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDescripcion))
            .addContainerGap())
    );
    pnlDetalleLayout.setVerticalGroup(pnlDetalleLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
        .addGroup(pnlDetalleLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(lblUnidadMedida)
            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(cbxUnidadMedida, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(lblCantidad)
            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(tfCantidad, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(lblDescripcion)
            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(tfDescripcion, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
            .addContainerGap(224, Short.MAX_VALUE))
    );

    tabbed.addTab("Detalle", pnlDetalle);

    separator.setMaximumSize(null);
    separator.setMinimumSize(null);
    separator.setPreferredSize(new Dimension(5, 5));

    btnNuevo.setIcon(FontIcon.of(RemixiconAL.ADD_LINE, 16, Color.decode("#FFFFFF")));
    btnNuevo.setText("Nuevo");
    btnNuevo.setMinimumSize(new Dimension(150, 30));
    btnNuevo.setPreferredSize(new Dimension(150, 30));

    btnGuardar.setIcon(FontIcon.of(RemixiconMZ.SAVE_LINE, 16, Color.decode("#FFFFFF")));
    btnGuardar.setText("Guardar");
    btnGuardar.setEnabled(false);
    btnGuardar.setMinimumSize(new Dimension(150, 30));
    btnGuardar.setPreferredSize(new Dimension(150, 30));

    btnLimpiar.setIcon(FontIcon.of(RemixiconAL.ERASER_LINE, 16, Color.decode("#FFFFFF")));
    btnLimpiar.setText("Limpiar");
    btnLimpiar.setEnabled(false);
    btnLimpiar.setMinimumSize(new Dimension(150, 30));
    btnLimpiar.setPreferredSize(new Dimension(150, 30));

        GroupLayout layout = new GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(btnNuevo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnGuardar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnLimpiar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addComponent(separator, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tabbed, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
    );
    layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
        .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(tabbed, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(separator, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                .addComponent(btnGuardar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(btnLimpiar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(btnNuevo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .addContainerGap())
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public JButton btnAdquirienteDocumentoIdentidad;
    public JButton btnGuardar;
    public JButton btnLimpiar;
    public JButton btnNuevo;
    public JComboBox<String> cbxAdquirienteTipoDocumentoIdentidad;
    public JComboBox<String> cbxMoneda;
    public JComboBox<String> cbxSerie;
    public JComboBox<String> cbxTipo;
    public JComboBox<String> cbxTipoOperacion;
    public JComboBox<String> cbxUnidadMedida;
    public JXDatePicker dpFecha;
    public JLabel lblAdquirienteNombre;
    public JLabel lblAdquirienteTipoDocumentoIdentidad;
    public JLabel lblCantidad;
    public JLabel lblCorrelativo;
    public JLabel lblDescripcion;
    public JLabel lblFecha;
    public JLabel lblMoneda;
    public JLabel lblSerie;
    public JLabel lblTipo;
    public JLabel lblTipoOperacion;
    public JLabel lblUnidadMedida;
    public JPanel pnlAdquiriente;
    public JPanel pnlDetalle;
    public JPanel pnlEncabezado;
    public JSeparator separator;
    public JTabbedPane tabbed;
    public JTextField tfAdquirienteDocumentoIdentidad;
    public JTextField tfAdquirienteNombre;
    public JTextField tfCantidad;
    public JTextField tfCorrelativo;
    public JTextField tfDescripcion;
    // End of variables declaration//GEN-END:variables
}
