/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.anthonyponte.jepinsa.view;

import java.awt.Color;
import java.awt.Dimension;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.GroupLayout;
import javax.swing.JInternalFrame;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.JSplitPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.JXDatePicker;
import org.kordamp.ikonli.remixicon.RemixiconAL;
import org.kordamp.ikonli.swing.FontIcon;

/**
 *
 * @author AnthonyPonte
 */
public class TableIFrame extends JInternalFrame {

    /**
     * Creates new form TablaIFrame
     */
    public TableIFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpMesAno = new JXDatePicker();
        tfFiltrar = new JTextField();
        split = new JSplitPane();
        spEncabezado = new JScrollPane();
        tblEncabezado = new JTable();
        spDetalle = new JScrollPane();
        tblDetalle = new JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setFrameIcon(FontIcon.of(RemixiconAL.CALENDAR_2_LINE, 16, Color.decode("#f7d117")));
        setMaximumSize(null);
        setMinimumSize(new Dimension(800, 600));
        setPreferredSize(new Dimension(800, 600));

        dpMesAno.setDate(new Date());
        dpMesAno.setFormats(new SimpleDateFormat("MMMM y"));
        dpMesAno.setMaximumSize(null);
        dpMesAno.setMinimumSize(null);
        dpMesAno.setPreferredSize(new Dimension(125, 30));
        dpMesAno.getEditor().setEditable(false);

        tfFiltrar.setMinimumSize(new Dimension(300, 30));
        tfFiltrar.setPreferredSize(new Dimension(300, 30));
        tfFiltrar.putClientProperty("JTextField.leadingIcon", FontIcon.of(RemixiconAL.FILTER_LINE, 16, Color.decode("#FFFFFF")));
        tfFiltrar.putClientProperty("JTextField.placeholderText", "Filtrar");
        tfFiltrar.putClientProperty("JTextField.showClearButton", true);

        split.setDividerLocation(300);
        split.setDividerSize(6);
        split.setOrientation(JSplitPane.VERTICAL_SPLIT);
        split.setResizeWeight(1.0);

        tblEncabezado.setModel(new DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblEncabezado.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tblEncabezado.setColumnSelectionAllowed(true);
        tblEncabezado.getTableHeader().setReorderingAllowed(false);
        spEncabezado.setViewportView(tblEncabezado);
        tblEncabezado.getColumnModel().getSelectionModel().setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        split.setLeftComponent(spEncabezado);

        tblDetalle.setModel(new DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblDetalle.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tblDetalle.getTableHeader().setReorderingAllowed(false);
        spDetalle.setViewportView(tblDetalle);

        split.setRightComponent(spDetalle);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(tfFiltrar, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(split, GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(dpMesAno, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dpMesAno, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfFiltrar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(split, GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public JXDatePicker dpMesAno;
    public JScrollPane spDetalle;
    public JScrollPane spEncabezado;
    public JSplitPane split;
    public JTable tblDetalle;
    public JTable tblEncabezado;
    public JTextField tfFiltrar;
    // End of variables declaration//GEN-END:variables
}
