/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.anthonyponte.jbill.view;

import com.anthonyponte.jbill.filter.IntegerFilter;
import com.anthonyponte.jbill.filter.SerieFilter;
import com.anthonyponte.jbill.model.TipoDocumento;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListCellRenderer;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JSeparator;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.text.AbstractDocument;
import org.kordamp.ikonli.remixicon.RemixiconAL;
import org.kordamp.ikonli.swing.FontIcon;

/**
 *
 * @author anthony
 */
public class StatusIFrame extends JInternalFrame {

    /**
     * Creates new form VoidedDocumentsIFrame
     */
    public StatusIFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTipo = new JLabel();
        cbxTipo = new JComboBox<>();
        lblSerie = new JLabel();
        tfSerie = new JTextField();
        lblCorrelativo = new JLabel();
        tfCorrelativo = new JTextField();
        lblEstado = new JLabel();
        tfEstado = new JTextField();
        separator = new JSeparator();
        btnNuevo = new JButton();
        btnLimpiar = new JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Status");
        setFrameIcon(FontIcon.of(RemixiconAL.CHECK_LINE, 16, Color.decode("#f7d117")));
        setMaximumSize(null);
        setMinimumSize(null);

        lblTipo.setFont(lblTipo.getFont().deriveFont(lblTipo.getFont().getStyle() | Font.BOLD, lblTipo.getFont().getSize()-2));
        lblTipo.setText("Tipo");

        cbxTipo.setModel(new DefaultComboBoxModel(new TipoDocumento[] {
            new TipoDocumento("01", "Factura"),
            new TipoDocumento("03", "Boleta de venta"),
            new TipoDocumento("07", "Nota de crédito"),
            new TipoDocumento("08", "Nota de débito")
        }));
        cbxTipo.setSelectedIndex(-1);
        cbxTipo.setMaximumSize(null);
        cbxTipo.setPreferredSize(new Dimension(150, 30));
        cbxTipo.setRenderer(new DefaultListCellRenderer(){
            @Override
            public Component getListCellRendererComponent(
                JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (value instanceof TipoDocumento) {
                    TipoDocumento tipoDocumento = (TipoDocumento) value;
                    setText(tipoDocumento.getDescripcion());
                }
                return this;
            }
        });

        lblSerie.setFont(lblSerie.getFont().deriveFont(lblSerie.getFont().getStyle() | Font.BOLD, lblSerie.getFont().getSize()-2));
        lblSerie.setText("Serie");

        tfSerie.setMaximumSize(null);
        tfSerie.setMinimumSize(null);
        tfSerie.setPreferredSize(new Dimension(150, 30));
        AbstractDocument docSerie = (AbstractDocument) tfSerie.getDocument();
        docSerie.setDocumentFilter(new SerieFilter('F'));

        lblCorrelativo.setFont(lblCorrelativo.getFont().deriveFont(lblCorrelativo.getFont().getStyle() | Font.BOLD, lblCorrelativo.getFont().getSize()-2));
        lblCorrelativo.setText("Correlativo");

        tfCorrelativo.setMaximumSize(null);
        tfCorrelativo.setMinimumSize(null);
        tfCorrelativo.setPreferredSize(new Dimension(150, 30));
        AbstractDocument docRuc = (AbstractDocument) tfCorrelativo.getDocument();
        docRuc.setDocumentFilter(new IntegerFilter(8));

        lblEstado.setFont(lblEstado.getFont().deriveFont(lblEstado.getFont().getStyle() | Font.BOLD, lblEstado.getFont().getSize()-2));
        lblEstado.setText("Estado");

        tfEstado.setMaximumSize(null);
        tfEstado.setMinimumSize(null);
        tfEstado.setPreferredSize(new Dimension(150, 30));

        separator.setMaximumSize(null);
        separator.setMinimumSize(null);
        separator.setPreferredSize(new Dimension(5, 5));

        btnNuevo.setIcon(FontIcon.of(RemixiconAL.CHECK_LINE, 16, Color.decode("#FFFFFF")));
        btnNuevo.setText("getStatus");
        btnNuevo.setMinimumSize(new Dimension(150, 30));
        btnNuevo.setPreferredSize(new Dimension(150, 30));

        btnLimpiar.setIcon(FontIcon.of(RemixiconAL.FILE_ZIP_LINE, 16, Color.decode("#FFFFFF")));
        btnLimpiar.setText("getStatusCdr");
        btnLimpiar.setEnabled(false);
        btnLimpiar.setMinimumSize(new Dimension(150, 30));
        btnLimpiar.setPreferredSize(new Dimension(150, 30));

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(separator, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfCorrelativo, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfSerie, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxTipo, GroupLayout.Alignment.TRAILING, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfEstado, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNuevo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLimpiar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblCorrelativo)
                            .addComponent(lblSerie)
                            .addComponent(lblTipo)
                            .addComponent(lblEstado))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTipo)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxTipo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSerie)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfSerie, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCorrelativo)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfCorrelativo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEstado)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfEstado, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(separator, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tfEstado.setEditable(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public JButton btnLimpiar;
    public JButton btnNuevo;
    public JComboBox<String> cbxTipo;
    public JLabel lblCorrelativo;
    public JLabel lblEstado;
    public JLabel lblSerie;
    public JLabel lblTipo;
    public JSeparator separator;
    public JTextField tfCorrelativo;
    public JTextField tfEstado;
    public JTextField tfSerie;
    // End of variables declaration//GEN-END:variables
}
